# Generated by Django 2.2 on 2019-09-25 14:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='Content', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
